# Generated by Django 4.1.5 on 2023-01-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactmcq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='title',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
